### ISSUE TITLE
Some Source endpoints don't show up in Endpoint Aliases

### ISSUE THREAD

**Issue by jashnani** [ni/niveristand-routing-and-faulting-custom-device#149] opened 2019-11-01 16:08 UTC
I can't alias some source endpoints.

Some source endpoints don't show up in State/Connection Configuration because there's isn't anything to connect to.....that behavior seems fine. However I could see the user wanting to alias source channels if they intend to reuse the channel at a later point in time (i.e change it's endpoint configuration to Load and use it in connection)

**Reproduction Steps**
1. Autodetect SLSC 12251
2. Mark DUT_Ch1 and Load_Ch1 as source channels
3. In Routing and Faulting Custom Device, select Endpoint Aliases
4. Notice that Load_Ch1 is not shown in the Endpoints dropdown.

**Comment by rtzoeller** [comment] 2019-11-01 16:14
The SLSC Switch custom device currently does not publish endpoints that have no possible connections. This was a conscious decision on my behalf during development, since the endpoints cannot be meaningfully used, but it may not be the correct one.

@jashnani what use case do you see value in allowing aliases of endpoints which cannot be used to make connections?

**Comment by rtzoeller** [comment] 2019-11-01 18:14
I have a fix for this prototyped on the `dev/show_unconnectable_source_endpoints` branch, but it will likely need to be rebased and partially fixed up once other changes go in due to merge conflicts.

**Comment by Karl-G1** [comment] 2019-11-12 14:46
Closing as intended behavior. This a subjective design decision, but it seems that showing un-connectable endpoints in aliases is just adding another step for confusion. When you get to the connection endpoint assignment page, you would not see the aliased endpoint since it cannot be connected to any destinations.

**Closed by Karl-G1** 2019-11-12 14:46 UTC
Labels: bug
